var annotated_dup =
[
    [ "Data", "namespace_data.html", [
      [ "NodeData", "class_data_1_1_node_data.html", "class_data_1_1_node_data" ],
      [ "NodeSample", "class_data_1_1_node_sample.html", "class_data_1_1_node_sample" ],
      [ "NodeSpecimen", "class_data_1_1_node_specimen.html", "class_data_1_1_node_specimen" ]
    ] ],
    [ "DatabaseError", "namespace_database_error.html", [
      [ "ConfigurationError", "class_database_error_1_1_configuration_error.html", "class_database_error_1_1_configuration_error" ],
      [ "ConnectionError", "class_database_error_1_1_connection_error.html", "class_database_error_1_1_connection_error" ],
      [ "QueryDeleteError", "class_database_error_1_1_query_delete_error.html", "class_database_error_1_1_query_delete_error" ],
      [ "QueryInsertError", "class_database_error_1_1_query_insert_error.html", "class_database_error_1_1_query_insert_error" ],
      [ "QuerySelectError", "class_database_error_1_1_query_select_error.html", "class_database_error_1_1_query_select_error" ],
      [ "QueryUpdateError", "class_database_error_1_1_query_update_error.html", "class_database_error_1_1_query_update_error" ]
    ] ],
    [ "FrontClases", "namespace_front_clases.html", [
      [ "NodeConditionalPeriod", "class_front_clases_1_1_node_conditional_period.html", "class_front_clases_1_1_node_conditional_period" ],
      [ "NodeEndCap", "class_front_clases_1_1_node_end_cap.html", "class_front_clases_1_1_node_end_cap" ],
      [ "NodeEnviroment", "class_front_clases_1_1_node_enviroment.html", "class_front_clases_1_1_node_enviroment" ],
      [ "NodeMaterial", "class_front_clases_1_1_node_material.html", "class_front_clases_1_1_node_material" ],
      [ "NodeOperator", "class_front_clases_1_1_node_operator.html", "class_front_clases_1_1_node_operator" ],
      [ "NodeSetting", "class_front_clases_1_1_node_setting.html", "class_front_clases_1_1_node_setting" ],
      [ "NodeSpecification", "class_front_clases_1_1_node_specification.html", "class_front_clases_1_1_node_specification" ],
      [ "NodeStandard", "class_front_clases_1_1_node_standard.html", "class_front_clases_1_1_node_standard" ],
      [ "NodeTestType", "class_front_clases_1_1_node_test_type.html", "class_front_clases_1_1_node_test_type" ]
    ] ],
    [ "Schemas", "namespace_schemas.html", [
      [ "Data", "class_schemas_1_1_data.html", "class_schemas_1_1_data" ],
      [ "Static", "class_schemas_1_1_static.html", "class_schemas_1_1_static" ]
    ] ],
    [ "Ui", "namespace_ui.html", [
      [ "DataVisualizerWindow", "class_ui_1_1_data_visualizer_window.html", null ],
      [ "DBConfig", "class_ui_1_1_d_b_config.html", null ],
      [ "serialConfig", "class_ui_1_1serial_config.html", null ],
      [ "SetStation", "class_ui_1_1_set_station.html", null ]
    ] ],
    [ "DatabaseManager", "class_database_manager.html", null ],
    [ "DataVisualizerWindow", "class_data_visualizer_window.html", "class_data_visualizer_window" ],
    [ "DBConfig", "class_d_b_config.html", "class_d_b_config" ],
    [ "PressureTempGraph", "class_pressure_temp_graph.html", "class_pressure_temp_graph" ],
    [ "QCPAbstractItem", "class_q_c_p_abstract_item.html", "class_q_c_p_abstract_item" ],
    [ "QCPAbstractLegendItem", "class_q_c_p_abstract_legend_item.html", "class_q_c_p_abstract_legend_item" ],
    [ "QCPAbstractPaintBuffer", "class_q_c_p_abstract_paint_buffer.html", "class_q_c_p_abstract_paint_buffer" ],
    [ "QCPAbstractPlottable", "class_q_c_p_abstract_plottable.html", "class_q_c_p_abstract_plottable" ],
    [ "QCPAbstractPlottable1D", "class_q_c_p_abstract_plottable1_d.html", "class_q_c_p_abstract_plottable1_d" ],
    [ "QCPAxis", "class_q_c_p_axis.html", "class_q_c_p_axis" ],
    [ "QCPAxisPainterPrivate", "class_q_c_p_axis_painter_private.html", "class_q_c_p_axis_painter_private" ],
    [ "QCPAxisRect", "class_q_c_p_axis_rect.html", "class_q_c_p_axis_rect" ],
    [ "QCPAxisTicker", "class_q_c_p_axis_ticker.html", "class_q_c_p_axis_ticker" ],
    [ "QCPAxisTickerDateTime", "class_q_c_p_axis_ticker_date_time.html", "class_q_c_p_axis_ticker_date_time" ],
    [ "QCPAxisTickerFixed", "class_q_c_p_axis_ticker_fixed.html", "class_q_c_p_axis_ticker_fixed" ],
    [ "QCPAxisTickerLog", "class_q_c_p_axis_ticker_log.html", "class_q_c_p_axis_ticker_log" ],
    [ "QCPAxisTickerPi", "class_q_c_p_axis_ticker_pi.html", "class_q_c_p_axis_ticker_pi" ],
    [ "QCPAxisTickerText", "class_q_c_p_axis_ticker_text.html", "class_q_c_p_axis_ticker_text" ],
    [ "QCPAxisTickerTime", "class_q_c_p_axis_ticker_time.html", "class_q_c_p_axis_ticker_time" ],
    [ "QCPBars", "class_q_c_p_bars.html", "class_q_c_p_bars" ],
    [ "QCPBarsData", "class_q_c_p_bars_data.html", "class_q_c_p_bars_data" ],
    [ "QCPBarsGroup", "class_q_c_p_bars_group.html", "class_q_c_p_bars_group" ],
    [ "QCPColorGradient", "class_q_c_p_color_gradient.html", "class_q_c_p_color_gradient" ],
    [ "QCPColorMap", "class_q_c_p_color_map.html", "class_q_c_p_color_map" ],
    [ "QCPColorMapData", "class_q_c_p_color_map_data.html", "class_q_c_p_color_map_data" ],
    [ "QCPColorScale", "class_q_c_p_color_scale.html", "class_q_c_p_color_scale" ],
    [ "QCPColorScaleAxisRectPrivate", "class_q_c_p_color_scale_axis_rect_private.html", "class_q_c_p_color_scale_axis_rect_private" ],
    [ "QCPCurve", "class_q_c_p_curve.html", "class_q_c_p_curve" ],
    [ "QCPCurveData", "class_q_c_p_curve_data.html", "class_q_c_p_curve_data" ],
    [ "QCPDataContainer", "class_q_c_p_data_container.html", "class_q_c_p_data_container" ],
    [ "QCPDataRange", "class_q_c_p_data_range.html", "class_q_c_p_data_range" ],
    [ "QCPDataSelection", "class_q_c_p_data_selection.html", "class_q_c_p_data_selection" ],
    [ "QCPErrorBars", "class_q_c_p_error_bars.html", "class_q_c_p_error_bars" ],
    [ "QCPErrorBarsData", "class_q_c_p_error_bars_data.html", "class_q_c_p_error_bars_data" ],
    [ "QCPFinancial", "class_q_c_p_financial.html", "class_q_c_p_financial" ],
    [ "QCPFinancialData", "class_q_c_p_financial_data.html", "class_q_c_p_financial_data" ],
    [ "QCPGraph", "class_q_c_p_graph.html", "class_q_c_p_graph" ],
    [ "QCPGraphData", "class_q_c_p_graph_data.html", "class_q_c_p_graph_data" ],
    [ "QCPGrid", "class_q_c_p_grid.html", "class_q_c_p_grid" ],
    [ "QCPItemAnchor", "class_q_c_p_item_anchor.html", "class_q_c_p_item_anchor" ],
    [ "QCPItemBracket", "class_q_c_p_item_bracket.html", "class_q_c_p_item_bracket" ],
    [ "QCPItemCurve", "class_q_c_p_item_curve.html", "class_q_c_p_item_curve" ],
    [ "QCPItemEllipse", "class_q_c_p_item_ellipse.html", "class_q_c_p_item_ellipse" ],
    [ "QCPItemLine", "class_q_c_p_item_line.html", "class_q_c_p_item_line" ],
    [ "QCPItemPixmap", "class_q_c_p_item_pixmap.html", "class_q_c_p_item_pixmap" ],
    [ "QCPItemPosition", "class_q_c_p_item_position.html", "class_q_c_p_item_position" ],
    [ "QCPItemRect", "class_q_c_p_item_rect.html", "class_q_c_p_item_rect" ],
    [ "QCPItemStraightLine", "class_q_c_p_item_straight_line.html", "class_q_c_p_item_straight_line" ],
    [ "QCPItemText", "class_q_c_p_item_text.html", "class_q_c_p_item_text" ],
    [ "QCPItemTracer", "class_q_c_p_item_tracer.html", "class_q_c_p_item_tracer" ],
    [ "QCPLabelPainterPrivate", "class_q_c_p_label_painter_private.html", "class_q_c_p_label_painter_private" ],
    [ "QCPLayer", "class_q_c_p_layer.html", "class_q_c_p_layer" ],
    [ "QCPLayerable", "class_q_c_p_layerable.html", "class_q_c_p_layerable" ],
    [ "QCPLayout", "class_q_c_p_layout.html", "class_q_c_p_layout" ],
    [ "QCPLayoutElement", "class_q_c_p_layout_element.html", "class_q_c_p_layout_element" ],
    [ "QCPLayoutGrid", "class_q_c_p_layout_grid.html", "class_q_c_p_layout_grid" ],
    [ "QCPLayoutInset", "class_q_c_p_layout_inset.html", "class_q_c_p_layout_inset" ],
    [ "QCPLegend", "class_q_c_p_legend.html", "class_q_c_p_legend" ],
    [ "QCPLineEnding", "class_q_c_p_line_ending.html", "class_q_c_p_line_ending" ],
    [ "QCPMarginGroup", "class_q_c_p_margin_group.html", "class_q_c_p_margin_group" ],
    [ "QCPPaintBufferPixmap", "class_q_c_p_paint_buffer_pixmap.html", "class_q_c_p_paint_buffer_pixmap" ],
    [ "QCPPainter", "class_q_c_p_painter.html", "class_q_c_p_painter" ],
    [ "QCPPlottableInterface1D", "class_q_c_p_plottable_interface1_d.html", "class_q_c_p_plottable_interface1_d" ],
    [ "QCPPlottableLegendItem", "class_q_c_p_plottable_legend_item.html", "class_q_c_p_plottable_legend_item" ],
    [ "QCPPolarAxisAngular", "class_q_c_p_polar_axis_angular.html", "class_q_c_p_polar_axis_angular" ],
    [ "QCPPolarAxisRadial", "class_q_c_p_polar_axis_radial.html", "class_q_c_p_polar_axis_radial" ],
    [ "QCPPolarGraph", "class_q_c_p_polar_graph.html", "class_q_c_p_polar_graph" ],
    [ "QCPPolarGrid", "class_q_c_p_polar_grid.html", "class_q_c_p_polar_grid" ],
    [ "QCPPolarLegendItem", "class_q_c_p_polar_legend_item.html", "class_q_c_p_polar_legend_item" ],
    [ "QCPRange", "class_q_c_p_range.html", "class_q_c_p_range" ],
    [ "QCPScatterStyle", "class_q_c_p_scatter_style.html", "class_q_c_p_scatter_style" ],
    [ "QCPSelectionDecorator", "class_q_c_p_selection_decorator.html", "class_q_c_p_selection_decorator" ],
    [ "QCPSelectionDecoratorBracket", "class_q_c_p_selection_decorator_bracket.html", "class_q_c_p_selection_decorator_bracket" ],
    [ "QCPSelectionRect", "class_q_c_p_selection_rect.html", "class_q_c_p_selection_rect" ],
    [ "QCPStatisticalBox", "class_q_c_p_statistical_box.html", "class_q_c_p_statistical_box" ],
    [ "QCPStatisticalBoxData", "class_q_c_p_statistical_box_data.html", "class_q_c_p_statistical_box_data" ],
    [ "QCPTextElement", "class_q_c_p_text_element.html", "class_q_c_p_text_element" ],
    [ "QCPVector2D", "class_q_c_p_vector2_d.html", "class_q_c_p_vector2_d" ],
    [ "QCustomPlot", "class_q_custom_plot.html", "class_q_custom_plot" ],
    [ "serialConfig", "classserial_config.html", "classserial_config" ],
    [ "SerialPortReader", "class_serial_port_reader.html", "class_serial_port_reader" ],
    [ "SetStation", "class_set_station.html", "class_set_station" ],
    [ "SharedData", "class_shared_data.html", "class_shared_data" ],
    [ "sharedStations", "classshared_stations.html", "classshared_stations" ],
    [ "SimpleCrypt", "class_simple_crypt.html", "class_simple_crypt" ],
    [ "Station", "class_station.html", "class_station" ],
    [ "StationList", "class_station_list.html", "class_station_list" ],
    [ "StationUI", "class_station_u_i.html", "class_station_u_i" ],
    [ "Ui_DataVisualizerWindow", "class_ui___data_visualizer_window.html", "class_ui___data_visualizer_window" ],
    [ "Ui_DBConfig", "class_ui___d_b_config.html", "class_ui___d_b_config" ],
    [ "Ui_serialConfig", "class_ui__serial_config.html", "class_ui__serial_config" ],
    [ "Ui_SetStation", "class_ui___set_station.html", "class_ui___set_station" ]
];